CREATE TABLE [dbo].[Site] (
    [Id]   BIGINT        NOT NULL,
    [Name] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_Site] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
ALTER TABLE [dbo].[Site] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

